import { Lato, Roboto } from 'next/font/google'
import './globals.scss'

const robotoFont = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

const latoFont = Lato({
  weight: ['400', '700'],
  subsets: ['latin'],
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className={robotoFont.className}
        style={{'--primary-font': robotoFont.style.fontFamily, '--secondary-font': latoFont.style.fontFamily}}
        >{children}</body>
    </html>
  )
}
